// Generated from a public DIVIPOLA-derived municipality dataset
// (1103 municipios across 32 departments, Bogotá D.C. included under
// Cundinamarca — matches how the dataset itself lists it). See
// CityAutocomplete.tsx (the forward fix) and the city-cleanup admin tool
// (the backward fix) for how this is used — both need the SAME list so a
// value the cleanup tool maps something to is always one the live form
// would also accept.
//
// `label` is the canonical, STORED value (Person.city) — plain city name
// for the common case, "Ciudad, Departamento" only for the ~60 names that
// collide across more than one department (e.g. Armenia exists in both
// Antioquia and Quindío — without the department suffix those would
// silently merge into one city in stats/segments).
export interface ColombiaCity {
  label: string;
  city: string;
  department: string;
}

export const COLOMBIA_CITIES: ColombiaCity[] = [
  { label: "Abejorral", city: "Abejorral", department: "Antioquia" },
  { label: "Abriaquí", city: "Abriaquí", department: "Antioquia" },
  { label: "Acacías", city: "Acacías", department: "Meta" },
  { label: "Acandí", city: "Acandí", department: "Chocó" },
  { label: "Acevedo", city: "Acevedo", department: "Huila" },
  { label: "Achí", city: "Achí", department: "Bolívar" },
  { label: "Agrado", city: "Agrado", department: "Huila" },
  { label: "Agua de Dios", city: "Agua de Dios", department: "Cundinamarca" },
  { label: "Aguachica", city: "Aguachica", department: "Cesar" },
  { label: "Aguada", city: "Aguada", department: "Santander" },
  { label: "Aguadas", city: "Aguadas", department: "Caldas" },
  { label: "Aguazul", city: "Aguazul", department: "Casanare" },
  { label: "Agustín Codazzi", city: "Agustín Codazzi", department: "Cesar" },
  { label: "Aipe", city: "Aipe", department: "Huila" },
  { label: "Albania, Caquetá", city: "Albania", department: "Caquetá" },
  { label: "Albania, La Guajira", city: "Albania", department: "La Guajira" },
  { label: "Albania, Santander", city: "Albania", department: "Santander" },
  { label: "Albán", city: "Albán", department: "Cundinamarca" },
  { label: "Alcalá", city: "Alcalá", department: "Valle del Cauca" },
  { label: "Aldana", city: "Aldana", department: "Nariño" },
  { label: "Alejandría", city: "Alejandría", department: "Antioquia" },
  { label: "Algarrobo", city: "Algarrobo", department: "Magdalena" },
  { label: "Algeciras", city: "Algeciras", department: "Huila" },
  { label: "Almaguer", city: "Almaguer", department: "Cauca" },
  { label: "Almeida", city: "Almeida", department: "Boyacá" },
  { label: "Alpujarra", city: "Alpujarra", department: "Tolima" },
  { label: "Altamira", city: "Altamira", department: "Huila" },
  { label: "Alto Baudó", city: "Alto Baudó", department: "Chocó" },
  { label: "Altos del Rosario", city: "Altos del Rosario", department: "Bolívar" },
  { label: "Alvarado", city: "Alvarado", department: "Tolima" },
  { label: "Amagá", city: "Amagá", department: "Antioquia" },
  { label: "Amalfi", city: "Amalfi", department: "Antioquia" },
  { label: "Ambalema", city: "Ambalema", department: "Tolima" },
  { label: "Anapoima", city: "Anapoima", department: "Cundinamarca" },
  { label: "Ancuyá", city: "Ancuyá", department: "Nariño" },
  { label: "Andalucía", city: "Andalucía", department: "Valle del Cauca" },
  { label: "Andes", city: "Andes", department: "Antioquia" },
  { label: "Angelópolis", city: "Angelópolis", department: "Antioquia" },
  { label: "Angostura", city: "Angostura", department: "Antioquia" },
  { label: "Anolaima", city: "Anolaima", department: "Cundinamarca" },
  { label: "Anorí", city: "Anorí", department: "Antioquia" },
  { label: "Anserma", city: "Anserma", department: "Caldas" },
  { label: "Ansermanuevo", city: "Ansermanuevo", department: "Valle del Cauca" },
  { label: "Anzoátegui", city: "Anzoátegui", department: "Tolima" },
  { label: "Anzá", city: "Anzá", department: "Antioquia" },
  { label: "Apartadó", city: "Apartadó", department: "Antioquia" },
  { label: "Apulo", city: "Apulo", department: "Cundinamarca" },
  { label: "Apía", city: "Apía", department: "Risaralda" },
  { label: "Aquitania", city: "Aquitania", department: "Boyacá" },
  { label: "Aracataca", city: "Aracataca", department: "Magdalena" },
  { label: "Aranzazu", city: "Aranzazu", department: "Caldas" },
  { label: "Aratoca", city: "Aratoca", department: "Santander" },
  { label: "Arauca", city: "Arauca", department: "Arauca" },
  { label: "Arauquita", city: "Arauquita", department: "Arauca" },
  { label: "Arbeláez", city: "Arbeláez", department: "Cundinamarca" },
  { label: "Arboleda", city: "Arboleda", department: "Nariño" },
  { label: "Arboledas", city: "Arboledas", department: "Norte de Santander" },
  { label: "Arboletes", city: "Arboletes", department: "Antioquia" },
  { label: "Arcabuco", city: "Arcabuco", department: "Boyacá" },
  { label: "Arenal", city: "Arenal", department: "Bolívar" },
  { label: "Argelia, Antioquia", city: "Argelia", department: "Antioquia" },
  { label: "Argelia, Cauca", city: "Argelia", department: "Cauca" },
  { label: "Argelia, Valle del Cauca", city: "Argelia", department: "Valle del Cauca" },
  { label: "Ariguaní", city: "Ariguaní", department: "Magdalena" },
  { label: "Arjona", city: "Arjona", department: "Bolívar" },
  { label: "Armenia, Antioquia", city: "Armenia", department: "Antioquia" },
  { label: "Armenia, Quindío", city: "Armenia", department: "Quindío" },
  { label: "Armero", city: "Armero", department: "Tolima" },
  { label: "Arroyohondo", city: "Arroyohondo", department: "Bolívar" },
  { label: "Astrea", city: "Astrea", department: "Cesar" },
  { label: "Ataco", city: "Ataco", department: "Tolima" },
  { label: "Ayapel", city: "Ayapel", department: "Córdoba" },
  { label: "Bagadó", city: "Bagadó", department: "Chocó" },
  { label: "Bahía Solano", city: "Bahía Solano", department: "Chocó" },
  { label: "Bajo Baudó", city: "Bajo Baudó", department: "Chocó" },
  { label: "Balboa, Cauca", city: "Balboa", department: "Cauca" },
  { label: "Balboa, Risaralda", city: "Balboa", department: "Risaralda" },
  { label: "Baranoa", city: "Baranoa", department: "Atlántico" },
  { label: "Baraya", city: "Baraya", department: "Huila" },
  { label: "Barbacoas", city: "Barbacoas", department: "Nariño" },
  { label: "Barbosa, Antioquia", city: "Barbosa", department: "Antioquia" },
  { label: "Barbosa, Santander", city: "Barbosa", department: "Santander" },
  { label: "Barichara", city: "Barichara", department: "Santander" },
  { label: "Barranca de Upía", city: "Barranca de Upía", department: "Meta" },
  { label: "Barrancabermeja", city: "Barrancabermeja", department: "Santander" },
  { label: "Barrancas", city: "Barrancas", department: "La Guajira" },
  { label: "Barranco de Loba", city: "Barranco de Loba", department: "Bolívar" },
  { label: "Barranquilla", city: "Barranquilla", department: "Atlántico" },
  { label: "Becerril", city: "Becerril", department: "Cesar" },
  { label: "Belalcázar", city: "Belalcázar", department: "Caldas" },
  { label: "Bello", city: "Bello", department: "Antioquia" },
  { label: "Belmira", city: "Belmira", department: "Antioquia" },
  { label: "Beltrán", city: "Beltrán", department: "Cundinamarca" },
  { label: "Belén de Umbría", city: "Belén de Umbría", department: "Risaralda" },
  { label: "Belén de los Andaquíes", city: "Belén de los Andaquíes", department: "Caquetá" },
  { label: "Belén, Boyacá", city: "Belén", department: "Boyacá" },
  { label: "Belén, Nariño", city: "Belén", department: "Nariño" },
  { label: "Berbeo", city: "Berbeo", department: "Boyacá" },
  { label: "Betania", city: "Betania", department: "Antioquia" },
  { label: "Betulia, Antioquia", city: "Betulia", department: "Antioquia" },
  { label: "Betulia, Santander", city: "Betulia", department: "Santander" },
  { label: "Betéitiva", city: "Betéitiva", department: "Boyacá" },
  { label: "Bituima", city: "Bituima", department: "Cundinamarca" },
  { label: "Boavita", city: "Boavita", department: "Boyacá" },
  { label: "Bochalema", city: "Bochalema", department: "Norte de Santander" },
  { label: "Bogotá", city: "Bogotá", department: "Cundinamarca" },
  { label: "Bojacá", city: "Bojacá", department: "Cundinamarca" },
  { label: "Bojayá", city: "Bojayá", department: "Chocó" },
  { label: "Bolívar, Cauca", city: "Bolívar", department: "Cauca" },
  { label: "Bolívar, Santander", city: "Bolívar", department: "Santander" },
  { label: "Bolívar, Valle del Cauca", city: "Bolívar", department: "Valle del Cauca" },
  { label: "Bosconia", city: "Bosconia", department: "Cesar" },
  { label: "Boyacá", city: "Boyacá", department: "Boyacá" },
  { label: "Brazuelo de Papayal", city: "Brazuelo de Papayal", department: "Bolívar" },
  { label: "Briceño, Antioquia", city: "Briceño", department: "Antioquia" },
  { label: "Briceño, Boyacá", city: "Briceño", department: "Boyacá" },
  { label: "Bucaramanga", city: "Bucaramanga", department: "Santander" },
  { label: "Bucarasica", city: "Bucarasica", department: "Norte de Santander" },
  { label: "Buenaventura", city: "Buenaventura", department: "Valle del Cauca" },
  { label: "Buenavista, Boyacá", city: "Buenavista", department: "Boyacá" },
  { label: "Buenavista, Córdoba", city: "Buenavista", department: "Córdoba" },
  { label: "Buenavista, Quindío", city: "Buenavista", department: "Quindío" },
  { label: "Buenavista, Sucre", city: "Buenavista", department: "Sucre" },
  { label: "Buenos Aires", city: "Buenos Aires", department: "Cauca" },
  { label: "Buesaco", city: "Buesaco", department: "Nariño" },
  { label: "Buga", city: "Buga", department: "Valle del Cauca" },
  { label: "Bugalagrande", city: "Bugalagrande", department: "Valle del Cauca" },
  { label: "Buriticá", city: "Buriticá", department: "Antioquia" },
  { label: "Busbanzá", city: "Busbanzá", department: "Boyacá" },
  { label: "Cabrera, Cundinamarca", city: "Cabrera", department: "Cundinamarca" },
  { label: "Cabrera, Santander", city: "Cabrera", department: "Santander" },
  { label: "Cabuyaro", city: "Cabuyaro", department: "Meta" },
  { label: "Cachipay", city: "Cachipay", department: "Cundinamarca" },
  { label: "Caicedo", city: "Caicedo", department: "Antioquia" },
  { label: "Caicedonia", city: "Caicedonia", department: "Valle del Cauca" },
  { label: "Caimito", city: "Caimito", department: "Sucre" },
  { label: "Cajamarca", city: "Cajamarca", department: "Tolima" },
  { label: "Cajibío", city: "Cajibío", department: "Cauca" },
  { label: "Cajicá", city: "Cajicá", department: "Cundinamarca" },
  { label: "Calamar, Bolívar", city: "Calamar", department: "Bolívar" },
  { label: "Calamar, Guaviare", city: "Calamar", department: "Guaviare" },
  { label: "Calarcá", city: "Calarcá", department: "Quindío" },
  { label: "Caldas, Antioquia", city: "Caldas", department: "Antioquia" },
  { label: "Caldas, Boyacá", city: "Caldas", department: "Boyacá" },
  { label: "Caldono", city: "Caldono", department: "Cauca" },
  { label: "Cali", city: "Cali", department: "Valle del Cauca" },
  { label: "California", city: "California", department: "Santander" },
  { label: "Calima", city: "Calima", department: "Valle del Cauca" },
  { label: "Caloto", city: "Caloto", department: "Cauca" },
  { label: "Campamento", city: "Campamento", department: "Antioquia" },
  { label: "Campo de la Cruz", city: "Campo de la Cruz", department: "Atlántico" },
  { label: "Campoalegre", city: "Campoalegre", department: "Huila" },
  { label: "Campohermoso", city: "Campohermoso", department: "Boyacá" },
  { label: "Canalete", city: "Canalete", department: "Córdoba" },
  { label: "Candelaria, Atlántico", city: "Candelaria", department: "Atlántico" },
  { label: "Candelaria, Valle del Cauca", city: "Candelaria", department: "Valle del Cauca" },
  { label: "Cantagallo", city: "Cantagallo", department: "Bolívar" },
  { label: "Cantón de San Pablo", city: "Cantón de San Pablo", department: "Chocó" },
  { label: "Caparrapí", city: "Caparrapí", department: "Cundinamarca" },
  { label: "Capitanejo", city: "Capitanejo", department: "Santander" },
  { label: "Caracolí", city: "Caracolí", department: "Antioquia" },
  { label: "Caramanta", city: "Caramanta", department: "Antioquia" },
  { label: "Carcasí", city: "Carcasí", department: "Santander" },
  { label: "Carepa", city: "Carepa", department: "Antioquia" },
  { label: "Carmen de Apicalá", city: "Carmen de Apicalá", department: "Tolima" },
  { label: "Carmen de Carupa", city: "Carmen de Carupa", department: "Cundinamarca" },
  { label: "Carolina del Príncipe", city: "Carolina del Príncipe", department: "Antioquia" },
  { label: "Cartagena de Indias", city: "Cartagena de Indias", department: "Bolívar" },
  { label: "Cartagena del Chairá", city: "Cartagena del Chairá", department: "Caquetá" },
  { label: "Cartago", city: "Cartago", department: "Valle del Cauca" },
  { label: "Carurú", city: "Carurú", department: "Vaupés" },
  { label: "Casabianca", city: "Casabianca", department: "Tolima" },
  { label: "Castilla la Nueva", city: "Castilla la Nueva", department: "Meta" },
  { label: "Caucasia", city: "Caucasia", department: "Antioquia" },
  { label: "Cañasgordas", city: "Cañasgordas", department: "Antioquia" },
  { label: "Cepitá", city: "Cepitá", department: "Santander" },
  { label: "Cereté", city: "Cereté", department: "Córdoba" },
  { label: "Cerinza", city: "Cerinza", department: "Boyacá" },
  { label: "Cerrito", city: "Cerrito", department: "Santander" },
  { label: "Cerro de San Antonio", city: "Cerro de San Antonio", department: "Magdalena" },
  { label: "Chachagüí", city: "Chachagüí", department: "Nariño" },
  { label: "Chaguaní", city: "Chaguaní", department: "Cundinamarca" },
  { label: "Chalán", city: "Chalán", department: "Sucre" },
  { label: "Chaparral", city: "Chaparral", department: "Tolima" },
  { label: "Charalá", city: "Charalá", department: "Santander" },
  { label: "Charta", city: "Charta", department: "Santander" },
  { label: "Chibolo", city: "Chibolo", department: "Magdalena" },
  { label: "Chigorodó", city: "Chigorodó", department: "Antioquia" },
  { label: "Chima", city: "Chima", department: "Santander" },
  { label: "Chimichagua", city: "Chimichagua", department: "Cesar" },
  { label: "Chimá", city: "Chimá", department: "Córdoba" },
  { label: "Chinavita", city: "Chinavita", department: "Boyacá" },
  { label: "Chinchiná", city: "Chinchiná", department: "Caldas" },
  { label: "Chinácota", city: "Chinácota", department: "Norte de Santander" },
  { label: "Chinú", city: "Chinú", department: "Córdoba" },
  { label: "Chipaque", city: "Chipaque", department: "Cundinamarca" },
  { label: "Chipatá", city: "Chipatá", department: "Santander" },
  { label: "Chiquinquirá", city: "Chiquinquirá", department: "Boyacá" },
  { label: "Chiriguaná", city: "Chiriguaná", department: "Cesar" },
  { label: "Chiscas", city: "Chiscas", department: "Boyacá" },
  { label: "Chita", city: "Chita", department: "Boyacá" },
  { label: "Chitagá", city: "Chitagá", department: "Norte de Santander" },
  { label: "Chitaraque", city: "Chitaraque", department: "Boyacá" },
  { label: "Chivatá", city: "Chivatá", department: "Boyacá" },
  { label: "Chivor", city: "Chivor", department: "Boyacá" },
  { label: "Choachí", city: "Choachí", department: "Cundinamarca" },
  { label: "Chocontá", city: "Chocontá", department: "Cundinamarca" },
  { label: "Chámeza", city: "Chámeza", department: "Casanare" },
  { label: "Chía", city: "Chía", department: "Cundinamarca" },
  { label: "Chíquiza", city: "Chíquiza", department: "Boyacá" },
  { label: "Cicuco", city: "Cicuco", department: "Bolívar" },
  { label: "Cimitarra", city: "Cimitarra", department: "Santander" },
  { label: "Circasia", city: "Circasia", department: "Quindío" },
  { label: "Cisneros", city: "Cisneros", department: "Antioquia" },
  { label: "Ciudad Bolívar", city: "Ciudad Bolívar", department: "Antioquia" },
  { label: "Ciénaga", city: "Ciénaga", department: "Magdalena" },
  { label: "Ciénaga de Oro", city: "Ciénaga de Oro", department: "Córdoba" },
  { label: "Ciénega", city: "Ciénega", department: "Boyacá" },
  { label: "Clemencia", city: "Clemencia", department: "Bolívar" },
  { label: "Cocorná", city: "Cocorná", department: "Antioquia" },
  { label: "Coello", city: "Coello", department: "Tolima" },
  { label: "Cogua", city: "Cogua", department: "Cundinamarca" },
  { label: "Colombia", city: "Colombia", department: "Huila" },
  { label: "Colosó", city: "Colosó", department: "Sucre" },
  { label: "Colón, Nariño", city: "Colón", department: "Nariño" },
  { label: "Colón, Putumayo", city: "Colón", department: "Putumayo" },
  { label: "Concepción, Antioquia", city: "Concepción", department: "Antioquia" },
  { label: "Concepción, Santander", city: "Concepción", department: "Santander" },
  { label: "Concordia, Antioquia", city: "Concordia", department: "Antioquia" },
  { label: "Concordia, Magdalena", city: "Concordia", department: "Magdalena" },
  { label: "Condoto", city: "Condoto", department: "Chocó" },
  { label: "Confines", city: "Confines", department: "Santander" },
  { label: "Consacá", city: "Consacá", department: "Nariño" },
  { label: "Contadero", city: "Contadero", department: "Nariño" },
  { label: "Contratación", city: "Contratación", department: "Santander" },
  { label: "Convención", city: "Convención", department: "Norte de Santander" },
  { label: "Copacabana", city: "Copacabana", department: "Antioquia" },
  { label: "Coper", city: "Coper", department: "Boyacá" },
  { label: "Corinto", city: "Corinto", department: "Cauca" },
  { label: "Coromoro", city: "Coromoro", department: "Santander" },
  { label: "Corozal", city: "Corozal", department: "Sucre" },
  { label: "Corrales", city: "Corrales", department: "Boyacá" },
  { label: "Cota", city: "Cota", department: "Cundinamarca" },
  { label: "Cotorra", city: "Cotorra", department: "Córdoba" },
  { label: "Covarachía", city: "Covarachía", department: "Boyacá" },
  { label: "Coveñas", city: "Coveñas", department: "Sucre" },
  { label: "Coyaima", city: "Coyaima", department: "Tolima" },
  { label: "Cravo Norte", city: "Cravo Norte", department: "Arauca" },
  { label: "Cuaspud", city: "Cuaspud", department: "Nariño" },
  { label: "Cubarral", city: "Cubarral", department: "Meta" },
  { label: "Cubará", city: "Cubará", department: "Boyacá" },
  { label: "Cucaita", city: "Cucaita", department: "Boyacá" },
  { label: "Cucunubá", city: "Cucunubá", department: "Cundinamarca" },
  { label: "Cucutilla", city: "Cucutilla", department: "Norte de Santander" },
  { label: "Cumaral", city: "Cumaral", department: "Meta" },
  { label: "Cumaribo", city: "Cumaribo", department: "Vichada" },
  { label: "Cumbal", city: "Cumbal", department: "Nariño" },
  { label: "Cumbitara", city: "Cumbitara", department: "Nariño" },
  { label: "Cunday", city: "Cunday", department: "Tolima" },
  { label: "Curillo", city: "Curillo", department: "Caquetá" },
  { label: "Curití", city: "Curití", department: "Santander" },
  { label: "Curumaní", city: "Curumaní", department: "Cesar" },
  { label: "Cuítiva", city: "Cuítiva", department: "Boyacá" },
  { label: "Cáceres", city: "Cáceres", department: "Antioquia" },
  { label: "Cáchira", city: "Cáchira", department: "Norte de Santander" },
  { label: "Cácota", city: "Cácota", department: "Norte de Santander" },
  { label: "Cáqueza", city: "Cáqueza", department: "Cundinamarca" },
  { label: "Cértegui", city: "Cértegui", department: "Chocó" },
  { label: "Cómbita", city: "Cómbita", department: "Boyacá" },
  { label: "Córdoba, Bolívar", city: "Córdoba", department: "Bolívar" },
  { label: "Córdoba, Nariño", city: "Córdoba", department: "Nariño" },
  { label: "Córdoba, Quindío", city: "Córdoba", department: "Quindío" },
  { label: "Cúcuta", city: "Cúcuta", department: "Norte de Santander" },
  { label: "Dabeiba", city: "Dabeiba", department: "Antioquia" },
  { label: "Dagua", city: "Dagua", department: "Valle del Cauca" },
  { label: "Dibulla", city: "Dibulla", department: "La Guajira" },
  { label: "Distracción", city: "Distracción", department: "La Guajira" },
  { label: "Dolores", city: "Dolores", department: "Tolima" },
  { label: "Donmatías", city: "Donmatías", department: "Antioquia" },
  { label: "Dosquebradas", city: "Dosquebradas", department: "Risaralda" },
  { label: "Duitama", city: "Duitama", department: "Boyacá" },
  { label: "Duranía", city: "Duranía", department: "Norte de Santander" },
  { label: "Ebéjico", city: "Ebéjico", department: "Antioquia" },
  { label: "El Atrato", city: "El Atrato", department: "Chocó" },
  { label: "El Bagre", city: "El Bagre", department: "Antioquia" },
  { label: "El Banco", city: "El Banco", department: "Magdalena" },
  { label: "El Cairo", city: "El Cairo", department: "Valle del Cauca" },
  { label: "El Calvario", city: "El Calvario", department: "Meta" },
  { label: "El Carmen", city: "El Carmen", department: "Norte de Santander" },
  { label: "El Carmen de Atrato", city: "El Carmen de Atrato", department: "Chocó" },
  { label: "El Carmen de Bolívar", city: "El Carmen de Bolívar", department: "Bolívar" },
  { label: "El Carmen de Chucurí", city: "El Carmen de Chucurí", department: "Santander" },
  { label: "El Carmen de Viboral", city: "El Carmen de Viboral", department: "Antioquia" },
  { label: "El Carmen del Darién", city: "El Carmen del Darién", department: "Chocó" },
  { label: "El Castillo", city: "El Castillo", department: "Meta" },
  { label: "El Cerrito", city: "El Cerrito", department: "Valle del Cauca" },
  { label: "El Charco", city: "El Charco", department: "Nariño" },
  { label: "El Cocuy", city: "El Cocuy", department: "Boyacá" },
  { label: "El Colegio", city: "El Colegio", department: "Cundinamarca" },
  { label: "El Copey", city: "El Copey", department: "Cesar" },
  { label: "El Doncello", city: "El Doncello", department: "Caquetá" },
  { label: "El Dorado", city: "El Dorado", department: "Meta" },
  { label: "El Dovio", city: "El Dovio", department: "Valle del Cauca" },
  { label: "El Espinal", city: "El Espinal", department: "Tolima" },
  { label: "El Espino", city: "El Espino", department: "Boyacá" },
  { label: "El Guacamayo", city: "El Guacamayo", department: "Santander" },
  { label: "El Guamo", city: "El Guamo", department: "Bolívar" },
  { label: "El Molino", city: "El Molino", department: "La Guajira" },
  { label: "El Paso", city: "El Paso", department: "Cesar" },
  { label: "El Paujil", city: "El Paujil", department: "Caquetá" },
  { label: "El Peñol, Antioquia", city: "El Peñol", department: "Antioquia" },
  { label: "El Peñol, Nariño", city: "El Peñol", department: "Nariño" },
  { label: "El Peñón, Bolívar", city: "El Peñón", department: "Bolívar" },
  { label: "El Peñón, Cundinamarca", city: "El Peñón", department: "Cundinamarca" },
  { label: "El Peñón, Santander", city: "El Peñón", department: "Santander" },
  { label: "El Pital", city: "El Pital", department: "Huila" },
  { label: "El Piñón", city: "El Piñón", department: "Magdalena" },
  { label: "El Playón", city: "El Playón", department: "Santander" },
  { label: "El Retiro", city: "El Retiro", department: "Antioquia" },
  { label: "El Retorno", city: "El Retorno", department: "Guaviare" },
  { label: "El Retén", city: "El Retén", department: "Magdalena" },
  { label: "El Roble", city: "El Roble", department: "Sucre" },
  { label: "El Rosal", city: "El Rosal", department: "Cundinamarca" },
  { label: "El Rosario", city: "El Rosario", department: "Nariño" },
  { label: "El Santuario", city: "El Santuario", department: "Antioquia" },
  { label: "El Socorro", city: "El Socorro", department: "Santander" },
  { label: "El Tablón", city: "El Tablón", department: "Nariño" },
  { label: "El Tambo, Cauca", city: "El Tambo", department: "Cauca" },
  { label: "El Tambo, Nariño", city: "El Tambo", department: "Nariño" },
  { label: "El Tarra", city: "El Tarra", department: "Norte de Santander" },
  { label: "El Zulia", city: "El Zulia", department: "Norte de Santander" },
  { label: "El Águila", city: "El Águila", department: "Valle del Cauca" },
  { label: "Elías", city: "Elías", department: "Huila" },
  { label: "Encino", city: "Encino", department: "Santander" },
  { label: "Enciso", city: "Enciso", department: "Santander" },
  { label: "Entrerríos", city: "Entrerríos", department: "Antioquia" },
  { label: "Envigado", city: "Envigado", department: "Antioquia" },
  { label: "Facatativá", city: "Facatativá", department: "Cundinamarca" },
  { label: "Falán", city: "Falán", department: "Tolima" },
  { label: "Filadelfia", city: "Filadelfia", department: "Caldas" },
  { label: "Filandia", city: "Filandia", department: "Quindío" },
  { label: "Firavitoba", city: "Firavitoba", department: "Boyacá" },
  { label: "Flandes", city: "Flandes", department: "Tolima" },
  { label: "Florencia, Caquetá", city: "Florencia", department: "Caquetá" },
  { label: "Florencia, Cauca", city: "Florencia", department: "Cauca" },
  { label: "Floresta", city: "Floresta", department: "Boyacá" },
  { label: "Florida", city: "Florida", department: "Valle del Cauca" },
  { label: "Floridablanca", city: "Floridablanca", department: "Santander" },
  { label: "Florián", city: "Florián", department: "Santander" },
  { label: "Fonseca", city: "Fonseca", department: "La Guajira" },
  { label: "Fortul", city: "Fortul", department: "Arauca" },
  { label: "Fosca", city: "Fosca", department: "Cundinamarca" },
  { label: "Francisco Pizarro", city: "Francisco Pizarro", department: "Nariño" },
  { label: "Fredonia", city: "Fredonia", department: "Antioquia" },
  { label: "Fresno", city: "Fresno", department: "Tolima" },
  { label: "Frontino", city: "Frontino", department: "Antioquia" },
  { label: "Fuente de Oro", city: "Fuente de Oro", department: "Meta" },
  { label: "Fundación", city: "Fundación", department: "Magdalena" },
  { label: "Funes", city: "Funes", department: "Nariño" },
  { label: "Funza", city: "Funza", department: "Cundinamarca" },
  { label: "Fusagasugá", city: "Fusagasugá", department: "Cundinamarca" },
  { label: "Fómeque", city: "Fómeque", department: "Cundinamarca" },
  { label: "Fúquene", city: "Fúquene", department: "Cundinamarca" },
  { label: "Gachalá", city: "Gachalá", department: "Cundinamarca" },
  { label: "Gachancipá", city: "Gachancipá", department: "Cundinamarca" },
  { label: "Gachantivá", city: "Gachantivá", department: "Boyacá" },
  { label: "Gachetá", city: "Gachetá", department: "Cundinamarca" },
  { label: "Galapa", city: "Galapa", department: "Atlántico" },
  { label: "Galeras", city: "Galeras", department: "Sucre" },
  { label: "Galán", city: "Galán", department: "Santander" },
  { label: "Gama", city: "Gama", department: "Cundinamarca" },
  { label: "Gamarra", city: "Gamarra", department: "Cesar" },
  { label: "Garagoa", city: "Garagoa", department: "Boyacá" },
  { label: "Garzón", city: "Garzón", department: "Huila" },
  { label: "Gigante", city: "Gigante", department: "Huila" },
  { label: "Ginebra", city: "Ginebra", department: "Valle del Cauca" },
  { label: "Giraldo", city: "Giraldo", department: "Antioquia" },
  { label: "Girardot", city: "Girardot", department: "Cundinamarca" },
  { label: "Girardota", city: "Girardota", department: "Antioquia" },
  { label: "Girón", city: "Girón", department: "Santander" },
  { label: "González", city: "González", department: "Cesar" },
  { label: "Gramalote", city: "Gramalote", department: "Norte de Santander" },
  { label: "Granada, Antioquia", city: "Granada", department: "Antioquia" },
  { label: "Granada, Cundinamarca", city: "Granada", department: "Cundinamarca" },
  { label: "Granada, Meta", city: "Granada", department: "Meta" },
  { label: "Guaca", city: "Guaca", department: "Santander" },
  { label: "Guacamayas", city: "Guacamayas", department: "Boyacá" },
  { label: "Guacarí", city: "Guacarí", department: "Valle del Cauca" },
  { label: "Guachené", city: "Guachené", department: "Cauca" },
  { label: "Guachetá", city: "Guachetá", department: "Cundinamarca" },
  { label: "Guachucal", city: "Guachucal", department: "Nariño" },
  { label: "Guadalupe, Antioquia", city: "Guadalupe", department: "Antioquia" },
  { label: "Guadalupe, Huila", city: "Guadalupe", department: "Huila" },
  { label: "Guadalupe, Santander", city: "Guadalupe", department: "Santander" },
  { label: "Guaduas", city: "Guaduas", department: "Cundinamarca" },
  { label: "Guaitarilla", city: "Guaitarilla", department: "Nariño" },
  { label: "Gualmatán", city: "Gualmatán", department: "Nariño" },
  { label: "Guamal, Magdalena", city: "Guamal", department: "Magdalena" },
  { label: "Guamal, Meta", city: "Guamal", department: "Meta" },
  { label: "Guamo", city: "Guamo", department: "Tolima" },
  { label: "Guapotá", city: "Guapotá", department: "Santander" },
  { label: "Guapí", city: "Guapí", department: "Cauca" },
  { label: "Guaranda", city: "Guaranda", department: "Sucre" },
  { label: "Guarne", city: "Guarne", department: "Antioquia" },
  { label: "Guasca", city: "Guasca", department: "Cundinamarca" },
  { label: "Guatapé", city: "Guatapé", department: "Antioquia" },
  { label: "Guataquí", city: "Guataquí", department: "Cundinamarca" },
  { label: "Guatavita", city: "Guatavita", department: "Cundinamarca" },
  { label: "Guateque", city: "Guateque", department: "Boyacá" },
  { label: "Guavatá", city: "Guavatá", department: "Santander" },
  { label: "Guayabal de Síquima", city: "Guayabal de Síquima", department: "Cundinamarca" },
  { label: "Guayabetal", city: "Guayabetal", department: "Cundinamarca" },
  { label: "Guayatá", city: "Guayatá", department: "Boyacá" },
  { label: "Gutiérrez", city: "Gutiérrez", department: "Cundinamarca" },
  { label: "Guática", city: "Guática", department: "Risaralda" },
  { label: "Gámbita", city: "Gámbita", department: "Santander" },
  { label: "Gámeza", city: "Gámeza", department: "Boyacá" },
  { label: "Génova", city: "Génova", department: "Quindío" },
  { label: "Gómez Plata", city: "Gómez Plata", department: "Antioquia" },
  { label: "Güepsa", city: "Güepsa", department: "Santander" },
  { label: "Güicán", city: "Güicán", department: "Boyacá" },
  { label: "Hacarí", city: "Hacarí", department: "Norte de Santander" },
  { label: "Hatillo de Loba", city: "Hatillo de Loba", department: "Bolívar" },
  { label: "Hato", city: "Hato", department: "Santander" },
  { label: "Hato Corozal", city: "Hato Corozal", department: "Casanare" },
  { label: "Hatonuevo", city: "Hatonuevo", department: "La Guajira" },
  { label: "Heliconia", city: "Heliconia", department: "Antioquia" },
  { label: "Herrán", city: "Herrán", department: "Norte de Santander" },
  { label: "Herveo", city: "Herveo", department: "Tolima" },
  { label: "Hispania", city: "Hispania", department: "Antioquia" },
  { label: "Hobo", city: "Hobo", department: "Huila" },
  { label: "Honda", city: "Honda", department: "Tolima" },
  { label: "Ibagué", city: "Ibagué", department: "Tolima" },
  { label: "Icononzo", city: "Icononzo", department: "Tolima" },
  { label: "Iles", city: "Iles", department: "Nariño" },
  { label: "Imués", city: "Imués", department: "Nariño" },
  { label: "Inzá", city: "Inzá", department: "Cauca" },
  { label: "Inírida", city: "Inírida", department: "Guainía" },
  { label: "Ipiales", city: "Ipiales", department: "Nariño" },
  { label: "Isnos", city: "Isnos", department: "Huila" },
  { label: "Istmina", city: "Istmina", department: "Chocó" },
  { label: "Itagüí", city: "Itagüí", department: "Antioquia" },
  { label: "Ituango", city: "Ituango", department: "Antioquia" },
  { label: "Iza", city: "Iza", department: "Boyacá" },
  { label: "Jambaló", city: "Jambaló", department: "Cauca" },
  { label: "Jamundí", city: "Jamundí", department: "Valle del Cauca" },
  { label: "Jardín", city: "Jardín", department: "Antioquia" },
  { label: "Jenesano", city: "Jenesano", department: "Boyacá" },
  { label: "Jericó, Antioquia", city: "Jericó", department: "Antioquia" },
  { label: "Jericó, Boyacá", city: "Jericó", department: "Boyacá" },
  { label: "Jerusalén", city: "Jerusalén", department: "Cundinamarca" },
  { label: "Jesús María", city: "Jesús María", department: "Santander" },
  { label: "Jordán", city: "Jordán", department: "Santander" },
  { label: "Juan de Acosta", city: "Juan de Acosta", department: "Atlántico" },
  { label: "Junín", city: "Junín", department: "Cundinamarca" },
  { label: "Juradó", city: "Juradó", department: "Chocó" },
  { label: "La Apartada", city: "La Apartada", department: "Córdoba" },
  { label: "La Argentina", city: "La Argentina", department: "Huila" },
  { label: "La Belleza", city: "La Belleza", department: "Santander" },
  { label: "La Calera", city: "La Calera", department: "Cundinamarca" },
  { label: "La Capilla", city: "La Capilla", department: "Boyacá" },
  { label: "La Ceja", city: "La Ceja", department: "Antioquia" },
  { label: "La Celia", city: "La Celia", department: "Risaralda" },
  { label: "La Cruz", city: "La Cruz", department: "Nariño" },
  { label: "La Cumbre", city: "La Cumbre", department: "Valle del Cauca" },
  { label: "La Dorada", city: "La Dorada", department: "Caldas" },
  { label: "La Esperanza", city: "La Esperanza", department: "Norte de Santander" },
  { label: "La Estrella", city: "La Estrella", department: "Antioquia" },
  { label: "La Florida", city: "La Florida", department: "Nariño" },
  { label: "La Gloria (Cesar)", city: "La Gloria (Cesar)", department: "Cesar" },
  { label: "La Jagua de Ibirico", city: "La Jagua de Ibirico", department: "Cesar" },
  { label: "La Jagua del Pilar", city: "La Jagua del Pilar", department: "La Guajira" },
  { label: "La Llanada", city: "La Llanada", department: "Nariño" },
  { label: "La Macarena", city: "La Macarena", department: "Meta" },
  { label: "La Merced", city: "La Merced", department: "Caldas" },
  { label: "La Mesa", city: "La Mesa", department: "Cundinamarca" },
  { label: "La Montañita", city: "La Montañita", department: "Caquetá" },
  { label: "La Palma", city: "La Palma", department: "Cundinamarca" },
  { label: "La Paz, Cesar", city: "La Paz", department: "Cesar" },
  { label: "La Paz, Santander", city: "La Paz", department: "Santander" },
  { label: "La Peña", city: "La Peña", department: "Cundinamarca" },
  { label: "La Pintada", city: "La Pintada", department: "Antioquia" },
  { label: "La Plata", city: "La Plata", department: "Huila" },
  { label: "La Playa de Belén", city: "La Playa de Belén", department: "Norte de Santander" },
  { label: "La Primavera", city: "La Primavera", department: "Vichada" },
  { label: "La Salina", city: "La Salina", department: "Casanare" },
  { label: "La Sierra", city: "La Sierra", department: "Cauca" },
  { label: "La Tebaida", city: "La Tebaida", department: "Quindío" },
  { label: "La Tola", city: "La Tola", department: "Nariño" },
  { label: "La Unión, Antioquia", city: "La Unión", department: "Antioquia" },
  { label: "La Unión, Nariño", city: "La Unión", department: "Nariño" },
  { label: "La Unión, Sucre", city: "La Unión", department: "Sucre" },
  { label: "La Unión, Valle del Cauca", city: "La Unión", department: "Valle del Cauca" },
  { label: "La Uribe", city: "La Uribe", department: "Meta" },
  { label: "La Uvita", city: "La Uvita", department: "Boyacá" },
  { label: "La Vega, Cauca", city: "La Vega", department: "Cauca" },
  { label: "La Vega, Cundinamarca", city: "La Vega", department: "Cundinamarca" },
  { label: "La Victoria, Boyacá", city: "La Victoria", department: "Boyacá" },
  { label: "La Victoria, Valle del Cauca", city: "La Victoria", department: "Valle del Cauca" },
  { label: "La Virginia", city: "La Virginia", department: "Risaralda" },
  { label: "Labateca", city: "Labateca", department: "Norte de Santander" },
  { label: "Labranzagrande", city: "Labranzagrande", department: "Boyacá" },
  { label: "Landázuri", city: "Landázuri", department: "Santander" },
  { label: "Lebrija", city: "Lebrija", department: "Santander" },
  { label: "Leiva", city: "Leiva", department: "Nariño" },
  { label: "Lejanías", city: "Lejanías", department: "Meta" },
  { label: "Lenguazaque", city: "Lenguazaque", department: "Cundinamarca" },
  { label: "Leticia", city: "Leticia", department: "Amazonas" },
  { label: "Liborina", city: "Liborina", department: "Antioquia" },
  { label: "Linares", city: "Linares", department: "Nariño" },
  { label: "Litoral de San Juan", city: "Litoral de San Juan", department: "Chocó" },
  { label: "Lloró", city: "Lloró", department: "Chocó" },
  { label: "Lorica", city: "Lorica", department: "Córdoba" },
  { label: "Los Andes", city: "Los Andes", department: "Nariño" },
  { label: "Los Córdobas", city: "Los Córdobas", department: "Córdoba" },
  { label: "Los Palmitos", city: "Los Palmitos", department: "Sucre" },
  { label: "Los Patios", city: "Los Patios", department: "Norte de Santander" },
  { label: "Los Santos", city: "Los Santos", department: "Santander" },
  { label: "Lourdes", city: "Lourdes", department: "Norte de Santander" },
  { label: "Luruaco", city: "Luruaco", department: "Atlántico" },
  { label: "Lérida", city: "Lérida", department: "Tolima" },
  { label: "Líbano", city: "Líbano", department: "Tolima" },
  { label: "López de Micay", city: "López de Micay", department: "Cauca" },
  { label: "Macanal", city: "Macanal", department: "Boyacá" },
  { label: "Macaravita", city: "Macaravita", department: "Santander" },
  { label: "Maceo", city: "Maceo", department: "Antioquia" },
  { label: "Machetá", city: "Machetá", department: "Cundinamarca" },
  { label: "Madrid", city: "Madrid", department: "Cundinamarca" },
  { label: "Magangué", city: "Magangué", department: "Bolívar" },
  { label: "Magüí Payán", city: "Magüí Payán", department: "Nariño" },
  { label: "Mahates", city: "Mahates", department: "Bolívar" },
  { label: "Maicao", city: "Maicao", department: "La Guajira" },
  { label: "Majagual", city: "Majagual", department: "Sucre" },
  { label: "Malambo", city: "Malambo", department: "Atlántico" },
  { label: "Mallama", city: "Mallama", department: "Nariño" },
  { label: "Manatí", city: "Manatí", department: "Atlántico" },
  { label: "Manaure", city: "Manaure", department: "La Guajira" },
  { label: "Manaure Balcón del Cesar", city: "Manaure Balcón del Cesar", department: "Cesar" },
  { label: "Manizales", city: "Manizales", department: "Caldas" },
  { label: "Manta", city: "Manta", department: "Cundinamarca" },
  { label: "Manzanares", city: "Manzanares", department: "Caldas" },
  { label: "Maní", city: "Maní", department: "Casanare" },
  { label: "Mapiripán", city: "Mapiripán", department: "Meta" },
  { label: "Margarita", city: "Margarita", department: "Bolívar" },
  { label: "Marinilla", city: "Marinilla", department: "Antioquia" },
  { label: "Maripí", city: "Maripí", department: "Boyacá" },
  { label: "Mariquita", city: "Mariquita", department: "Tolima" },
  { label: "Marmato", city: "Marmato", department: "Caldas" },
  { label: "Marquetalia", city: "Marquetalia", department: "Caldas" },
  { label: "Marsella", city: "Marsella", department: "Risaralda" },
  { label: "Marulanda", city: "Marulanda", department: "Caldas" },
  { label: "María la Baja", city: "María la Baja", department: "Bolívar" },
  { label: "Matanza", city: "Matanza", department: "Santander" },
  { label: "Medellín", city: "Medellín", department: "Antioquia" },
  { label: "Medina", city: "Medina", department: "Cundinamarca" },
  { label: "Medio Atrato", city: "Medio Atrato", department: "Chocó" },
  { label: "Medio Baudó", city: "Medio Baudó", department: "Chocó" },
  { label: "Medio San Juan", city: "Medio San Juan", department: "Chocó" },
  { label: "Melgar", city: "Melgar", department: "Tolima" },
  { label: "Mercaderes", city: "Mercaderes", department: "Cauca" },
  { label: "Mesetas", city: "Mesetas", department: "Meta" },
  { label: "Milán", city: "Milán", department: "Caquetá" },
  { label: "Miraflores, Boyacá", city: "Miraflores", department: "Boyacá" },
  { label: "Miraflores, Guaviare", city: "Miraflores", department: "Guaviare" },
  { label: "Miranda", city: "Miranda", department: "Cauca" },
  { label: "Mistrató", city: "Mistrató", department: "Risaralda" },
  { label: "Mitú", city: "Mitú", department: "Vaupés" },
  { label: "Mocoa", city: "Mocoa", department: "Putumayo" },
  { label: "Mogotes", city: "Mogotes", department: "Santander" },
  { label: "Molagavita", city: "Molagavita", department: "Santander" },
  { label: "Momil", city: "Momil", department: "Córdoba" },
  { label: "Mompós", city: "Mompós", department: "Bolívar" },
  { label: "Mongua", city: "Mongua", department: "Boyacá" },
  { label: "Monguí", city: "Monguí", department: "Boyacá" },
  { label: "Moniquirá", city: "Moniquirá", department: "Boyacá" },
  { label: "Montebello", city: "Montebello", department: "Antioquia" },
  { label: "Montecristo", city: "Montecristo", department: "Bolívar" },
  { label: "Montelíbano", city: "Montelíbano", department: "Córdoba" },
  { label: "Montenegro", city: "Montenegro", department: "Quindío" },
  { label: "Monterrey", city: "Monterrey", department: "Casanare" },
  { label: "Montería", city: "Montería", department: "Córdoba" },
  { label: "Morales, Bolívar", city: "Morales", department: "Bolívar" },
  { label: "Morales, Cauca", city: "Morales", department: "Cauca" },
  { label: "Morelia", city: "Morelia", department: "Caquetá" },
  { label: "Morroa", city: "Morroa", department: "Sucre" },
  { label: "Mosquera, Cundinamarca", city: "Mosquera", department: "Cundinamarca" },
  { label: "Mosquera, Nariño", city: "Mosquera", department: "Nariño" },
  { label: "Motavita", city: "Motavita", department: "Boyacá" },
  { label: "Moñitos", city: "Moñitos", department: "Córdoba" },
  { label: "Murillo", city: "Murillo", department: "Tolima" },
  { label: "Murindó", city: "Murindó", department: "Antioquia" },
  { label: "Mutatá", city: "Mutatá", department: "Antioquia" },
  { label: "Mutiscua", city: "Mutiscua", department: "Norte de Santander" },
  { label: "Muzo", city: "Muzo", department: "Boyacá" },
  { label: "Málaga", city: "Málaga", department: "Santander" },
  { label: "Nariño, Antioquia", city: "Nariño", department: "Antioquia" },
  { label: "Nariño, Cundinamarca", city: "Nariño", department: "Cundinamarca" },
  { label: "Nariño, Nariño", city: "Nariño", department: "Nariño" },
  { label: "Natagaima", city: "Natagaima", department: "Tolima" },
  { label: "Nechí", city: "Nechí", department: "Antioquia" },
  { label: "Necoclí", city: "Necoclí", department: "Antioquia" },
  { label: "Neira", city: "Neira", department: "Caldas" },
  { label: "Neiva", city: "Neiva", department: "Huila" },
  { label: "Nemocón", city: "Nemocón", department: "Cundinamarca" },
  { label: "Nilo", city: "Nilo", department: "Cundinamarca" },
  { label: "Nimaima", city: "Nimaima", department: "Cundinamarca" },
  { label: "Nobsa", city: "Nobsa", department: "Boyacá" },
  { label: "Nocaima", city: "Nocaima", department: "Cundinamarca" },
  { label: "Norcasia", city: "Norcasia", department: "Caldas" },
  { label: "Norosí", city: "Norosí", department: "Bolívar" },
  { label: "Nueva Granada", city: "Nueva Granada", department: "Magdalena" },
  { label: "Nuevo Colón", city: "Nuevo Colón", department: "Boyacá" },
  { label: "Nunchía", city: "Nunchía", department: "Casanare" },
  { label: "Nuquí", city: "Nuquí", department: "Chocó" },
  { label: "Nátaga", city: "Nátaga", department: "Huila" },
  { label: "Nóvita", city: "Nóvita", department: "Chocó" },
  { label: "Obando", city: "Obando", department: "Valle del Cauca" },
  { label: "Ocamonte", city: "Ocamonte", department: "Santander" },
  { label: "Ocaña", city: "Ocaña", department: "Norte de Santander" },
  { label: "Oiba", city: "Oiba", department: "Santander" },
  { label: "Oicatá", city: "Oicatá", department: "Boyacá" },
  { label: "Olaya", city: "Olaya", department: "Antioquia" },
  { label: "Olaya Herrera", city: "Olaya Herrera", department: "Nariño" },
  { label: "Onzaga", city: "Onzaga", department: "Santander" },
  { label: "Oporapa", city: "Oporapa", department: "Huila" },
  { label: "Orito", city: "Orito", department: "Putumayo" },
  { label: "Orocué", city: "Orocué", department: "Casanare" },
  { label: "Ortega", city: "Ortega", department: "Tolima" },
  { label: "Ospina", city: "Ospina", department: "Nariño" },
  { label: "Otanche", city: "Otanche", department: "Boyacá" },
  { label: "Ovejas", city: "Ovejas", department: "Sucre" },
  { label: "Pachavita", city: "Pachavita", department: "Boyacá" },
  { label: "Pacho", city: "Pacho", department: "Cundinamarca" },
  { label: "Padilla", city: "Padilla", department: "Cauca" },
  { label: "Paicol", city: "Paicol", department: "Huila" },
  { label: "Pailitas", city: "Pailitas", department: "Cesar" },
  { label: "Paime", city: "Paime", department: "Cundinamarca" },
  { label: "Paipa", city: "Paipa", department: "Boyacá" },
  { label: "Pajarito", city: "Pajarito", department: "Boyacá" },
  { label: "Palermo", city: "Palermo", department: "Huila" },
  { label: "Palestina, Caldas", city: "Palestina", department: "Caldas" },
  { label: "Palestina, Huila", city: "Palestina", department: "Huila" },
  { label: "Palmar", city: "Palmar", department: "Santander" },
  { label: "Palmar de Varela", city: "Palmar de Varela", department: "Atlántico" },
  { label: "Palmas del Socorro", city: "Palmas del Socorro", department: "Santander" },
  { label: "Palmira", city: "Palmira", department: "Valle del Cauca" },
  { label: "Palocabildo", city: "Palocabildo", department: "Tolima" },
  { label: "Pamplona", city: "Pamplona", department: "Norte de Santander" },
  { label: "Pamplonita", city: "Pamplonita", department: "Norte de Santander" },
  { label: "Pandi", city: "Pandi", department: "Cundinamarca" },
  { label: "Panqueba", city: "Panqueba", department: "Boyacá" },
  { label: "Paratebueno", city: "Paratebueno", department: "Cundinamarca" },
  { label: "Pasca", city: "Pasca", department: "Cundinamarca" },
  { label: "Pasto", city: "Pasto", department: "Nariño" },
  { label: "Patía", city: "Patía", department: "Cauca" },
  { label: "Pauna", city: "Pauna", department: "Boyacá" },
  { label: "Paya", city: "Paya", department: "Boyacá" },
  { label: "Paz de Ariporo", city: "Paz de Ariporo", department: "Casanare" },
  { label: "Paz del Río", city: "Paz del Río", department: "Boyacá" },
  { label: "Pedraza", city: "Pedraza", department: "Magdalena" },
  { label: "Pelaya", city: "Pelaya", department: "Cesar" },
  { label: "Pensilvania", city: "Pensilvania", department: "Caldas" },
  { label: "Peque", city: "Peque", department: "Antioquia" },
  { label: "Pereira", city: "Pereira", department: "Risaralda" },
  { label: "Pesca", city: "Pesca", department: "Boyacá" },
  { label: "Piamonte", city: "Piamonte", department: "Cauca" },
  { label: "Piedecuesta", city: "Piedecuesta", department: "Santander" },
  { label: "Piedras", city: "Piedras", department: "Tolima" },
  { label: "Piendamó", city: "Piendamó", department: "Cauca" },
  { label: "Pijao", city: "Pijao", department: "Quindío" },
  { label: "Pijiño del Carmen", city: "Pijiño del Carmen", department: "Magdalena" },
  { label: "Pinchote", city: "Pinchote", department: "Santander" },
  { label: "Pinillos", city: "Pinillos", department: "Bolívar" },
  { label: "Piojó", city: "Piojó", department: "Atlántico" },
  { label: "Pisba", city: "Pisba", department: "Boyacá" },
  { label: "Pitalito", city: "Pitalito", department: "Huila" },
  { label: "Pivijay", city: "Pivijay", department: "Magdalena" },
  { label: "Planadas", city: "Planadas", department: "Tolima" },
  { label: "Planeta Rica", city: "Planeta Rica", department: "Córdoba" },
  { label: "Plato", city: "Plato", department: "Magdalena" },
  { label: "Policarpa", city: "Policarpa", department: "Nariño" },
  { label: "Polonuevo", city: "Polonuevo", department: "Atlántico" },
  { label: "Ponedera", city: "Ponedera", department: "Atlántico" },
  { label: "Popayán", city: "Popayán", department: "Cauca" },
  { label: "Pore", city: "Pore", department: "Casanare" },
  { label: "Potosí", city: "Potosí", department: "Nariño" },
  { label: "Pradera", city: "Pradera", department: "Valle del Cauca" },
  { label: "Prado", city: "Prado", department: "Tolima" },
  { label: "Providencia", city: "Providencia", department: "Nariño" },
  { label: "Providencia y Santa Catalina Islas", city: "Providencia y Santa Catalina Islas", department: "San Andrés y Providencia" },
  { label: "Pueblo Bello", city: "Pueblo Bello", department: "Cesar" },
  { label: "Pueblo Nuevo", city: "Pueblo Nuevo", department: "Córdoba" },
  { label: "Pueblo Rico", city: "Pueblo Rico", department: "Risaralda" },
  { label: "Pueblo Viejo", city: "Pueblo Viejo", department: "Magdalena" },
  { label: "Pueblorrico", city: "Pueblorrico", department: "Antioquia" },
  { label: "Puente Nacional", city: "Puente Nacional", department: "Santander" },
  { label: "Puerres", city: "Puerres", department: "Nariño" },
  { label: "Puerto Asís", city: "Puerto Asís", department: "Putumayo" },
  { label: "Puerto Berrío", city: "Puerto Berrío", department: "Antioquia" },
  { label: "Puerto Boyacá", city: "Puerto Boyacá", department: "Boyacá" },
  { label: "Puerto Caicedo", city: "Puerto Caicedo", department: "Putumayo" },
  { label: "Puerto Carreño", city: "Puerto Carreño", department: "Vichada" },
  { label: "Puerto Colombia", city: "Puerto Colombia", department: "Atlántico" },
  { label: "Puerto Concordia", city: "Puerto Concordia", department: "Meta" },
  { label: "Puerto Escondido", city: "Puerto Escondido", department: "Córdoba" },
  { label: "Puerto Gaitán", city: "Puerto Gaitán", department: "Meta" },
  { label: "Puerto Guzmán", city: "Puerto Guzmán", department: "Putumayo" },
  { label: "Puerto Leguízamo", city: "Puerto Leguízamo", department: "Putumayo" },
  { label: "Puerto Libertador", city: "Puerto Libertador", department: "Córdoba" },
  { label: "Puerto Lleras", city: "Puerto Lleras", department: "Meta" },
  { label: "Puerto López", city: "Puerto López", department: "Meta" },
  { label: "Puerto Nare", city: "Puerto Nare", department: "Antioquia" },
  { label: "Puerto Nariño", city: "Puerto Nariño", department: "Amazonas" },
  { label: "Puerto Parra", city: "Puerto Parra", department: "Santander" },
  { label: "Puerto Rico, Caquetá", city: "Puerto Rico", department: "Caquetá" },
  { label: "Puerto Rico, Meta", city: "Puerto Rico", department: "Meta" },
  { label: "Puerto Rondón", city: "Puerto Rondón", department: "Arauca" },
  { label: "Puerto Salgar", city: "Puerto Salgar", department: "Cundinamarca" },
  { label: "Puerto Santander", city: "Puerto Santander", department: "Norte de Santander" },
  { label: "Puerto Tejada", city: "Puerto Tejada", department: "Cauca" },
  { label: "Puerto Triunfo", city: "Puerto Triunfo", department: "Antioquia" },
  { label: "Puerto Wilches", city: "Puerto Wilches", department: "Santander" },
  { label: "Pulí", city: "Pulí", department: "Cundinamarca" },
  { label: "Pupiales", city: "Pupiales", department: "Nariño" },
  { label: "Puracé", city: "Puracé", department: "Cauca" },
  { label: "Purificación", city: "Purificación", department: "Tolima" },
  { label: "Purísima", city: "Purísima", department: "Córdoba" },
  { label: "Pácora", city: "Pácora", department: "Caldas" },
  { label: "Páez, Boyacá", city: "Páez", department: "Boyacá" },
  { label: "Páez, Cauca", city: "Páez", department: "Cauca" },
  { label: "Páramo", city: "Páramo", department: "Santander" },
  { label: "Quebradanegra", city: "Quebradanegra", department: "Cundinamarca" },
  { label: "Quetame", city: "Quetame", department: "Cundinamarca" },
  { label: "Quibdó", city: "Quibdó", department: "Chocó" },
  { label: "Quimbaya", city: "Quimbaya", department: "Quindío" },
  { label: "Quinchía", city: "Quinchía", department: "Risaralda" },
  { label: "Quipile", city: "Quipile", department: "Cundinamarca" },
  { label: "Quípama", city: "Quípama", department: "Boyacá" },
  { label: "Ragonvalia", city: "Ragonvalia", department: "Norte de Santander" },
  { label: "Ramiriquí", city: "Ramiriquí", department: "Boyacá" },
  { label: "Recetor", city: "Recetor", department: "Casanare" },
  { label: "Regidor", city: "Regidor", department: "Bolívar" },
  { label: "Remedios", city: "Remedios", department: "Antioquia" },
  { label: "Remolino", city: "Remolino", department: "Magdalena" },
  { label: "Repelón", city: "Repelón", department: "Atlántico" },
  { label: "Restrepo, Meta", city: "Restrepo", department: "Meta" },
  { label: "Restrepo, Valle del Cauca", city: "Restrepo", department: "Valle del Cauca" },
  { label: "Ricaurte, Cundinamarca", city: "Ricaurte", department: "Cundinamarca" },
  { label: "Ricaurte, Nariño", city: "Ricaurte", department: "Nariño" },
  { label: "Rioblanco", city: "Rioblanco", department: "Tolima" },
  { label: "Riofrío", city: "Riofrío", department: "Valle del Cauca" },
  { label: "Riohacha", city: "Riohacha", department: "La Guajira" },
  { label: "Rionegro, Antioquia", city: "Rionegro", department: "Antioquia" },
  { label: "Rionegro, Santander", city: "Rionegro", department: "Santander" },
  { label: "Riosucio, Caldas", city: "Riosucio", department: "Caldas" },
  { label: "Riosucio, Chocó", city: "Riosucio", department: "Chocó" },
  { label: "Risaralda", city: "Risaralda", department: "Caldas" },
  { label: "Rivera", city: "Rivera", department: "Huila" },
  { label: "Roberto Payán", city: "Roberto Payán", department: "Nariño" },
  { label: "Roldanillo", city: "Roldanillo", department: "Valle del Cauca" },
  { label: "Roncesvalles", city: "Roncesvalles", department: "Tolima" },
  { label: "Rondón", city: "Rondón", department: "Boyacá" },
  { label: "Rosas", city: "Rosas", department: "Cauca" },
  { label: "Rovira", city: "Rovira", department: "Tolima" },
  { label: "Ráquira", city: "Ráquira", department: "Boyacá" },
  { label: "Río Iró", city: "Río Iró", department: "Chocó" },
  { label: "Río Quito", city: "Río Quito", department: "Chocó" },
  { label: "Río Viejo", city: "Río Viejo", department: "Bolívar" },
  { label: "Río de Oro", city: "Río de Oro", department: "Cesar" },
  { label: "Sabana de Torres", city: "Sabana de Torres", department: "Santander" },
  { label: "Sabanagrande", city: "Sabanagrande", department: "Atlántico" },
  { label: "Sabanalarga, Antioquia", city: "Sabanalarga", department: "Antioquia" },
  { label: "Sabanalarga, Atlántico", city: "Sabanalarga", department: "Atlántico" },
  { label: "Sabanalarga, Casanare", city: "Sabanalarga", department: "Casanare" },
  { label: "Sabanas de San Ángel", city: "Sabanas de San Ángel", department: "Magdalena" },
  { label: "Sabaneta", city: "Sabaneta", department: "Antioquia" },
  { label: "Saboyá", city: "Saboyá", department: "Boyacá" },
  { label: "Sahagún", city: "Sahagún", department: "Córdoba" },
  { label: "Saladoblanco", city: "Saladoblanco", department: "Huila" },
  { label: "Salamina, Caldas", city: "Salamina", department: "Caldas" },
  { label: "Salamina, Magdalena", city: "Salamina", department: "Magdalena" },
  { label: "Salazar de Las Palmas", city: "Salazar de Las Palmas", department: "Norte de Santander" },
  { label: "Saldaña", city: "Saldaña", department: "Tolima" },
  { label: "Salento", city: "Salento", department: "Quindío" },
  { label: "Salgar", city: "Salgar", department: "Antioquia" },
  { label: "Samacá", city: "Samacá", department: "Boyacá" },
  { label: "Samaniego", city: "Samaniego", department: "Nariño" },
  { label: "Samaná", city: "Samaná", department: "Caldas" },
  { label: "Sampués", city: "Sampués", department: "Sucre" },
  { label: "San Agustín", city: "San Agustín", department: "Huila" },
  { label: "San Alberto", city: "San Alberto", department: "Cesar" },
  { label: "San Andrés de Cuerquia", city: "San Andrés de Cuerquia", department: "Antioquia" },
  { label: "San Andrés de Sotavento", city: "San Andrés de Sotavento", department: "Córdoba" },
  { label: "San Andrés, San Andrés y Providencia", city: "San Andrés", department: "San Andrés y Providencia" },
  { label: "San Andrés, Santander", city: "San Andrés", department: "Santander" },
  { label: "San Antero", city: "San Antero", department: "Córdoba" },
  { label: "San Antonio", city: "San Antonio", department: "Tolima" },
  { label: "San Antonio de Palmito", city: "San Antonio de Palmito", department: "Sucre" },
  { label: "San Antonio del Tequendama", city: "San Antonio del Tequendama", department: "Cundinamarca" },
  { label: "San Benito", city: "San Benito", department: "Santander" },
  { label: "San Benito Abad", city: "San Benito Abad", department: "Sucre" },
  { label: "San Bernardo del Viento", city: "San Bernardo del Viento", department: "Córdoba" },
  { label: "San Bernardo, Cundinamarca", city: "San Bernardo", department: "Cundinamarca" },
  { label: "San Bernardo, Nariño", city: "San Bernardo", department: "Nariño" },
  { label: "San Calixto", city: "San Calixto", department: "Norte de Santander" },
  { label: "San Carlos de Guaroa", city: "San Carlos de Guaroa", department: "Meta" },
  { label: "San Carlos, Antioquia", city: "San Carlos", department: "Antioquia" },
  { label: "San Carlos, Córdoba", city: "San Carlos", department: "Córdoba" },
  { label: "San Cayetano, Cundinamarca", city: "San Cayetano", department: "Cundinamarca" },
  { label: "San Cayetano, Norte de Santander", city: "San Cayetano", department: "Norte de Santander" },
  { label: "San Cristóbal", city: "San Cristóbal", department: "Bolívar" },
  { label: "San Diego", city: "San Diego", department: "Cesar" },
  { label: "San Eduardo", city: "San Eduardo", department: "Boyacá" },
  { label: "San Estanislao", city: "San Estanislao", department: "Bolívar" },
  { label: "San Fernando", city: "San Fernando", department: "Bolívar" },
  { label: "San Francisco, Antioquia", city: "San Francisco", department: "Antioquia" },
  { label: "San Francisco, Cundinamarca", city: "San Francisco", department: "Cundinamarca" },
  { label: "San Francisco, Putumayo", city: "San Francisco", department: "Putumayo" },
  { label: "San Gil", city: "San Gil", department: "Santander" },
  { label: "San Jacinto", city: "San Jacinto", department: "Bolívar" },
  { label: "San Jacinto del Cauca", city: "San Jacinto del Cauca", department: "Bolívar" },
  { label: "San Jerónimo", city: "San Jerónimo", department: "Antioquia" },
  { label: "San Joaquín", city: "San Joaquín", department: "Santander" },
  { label: "San José", city: "San José", department: "Caldas" },
  { label: "San José de Albán", city: "San José de Albán", department: "Nariño" },
  { label: "San José de Miranda", city: "San José de Miranda", department: "Santander" },
  { label: "San José de Pare", city: "San José de Pare", department: "Boyacá" },
  { label: "San José de Uré", city: "San José de Uré", department: "Córdoba" },
  { label: "San José de la Montaña", city: "San José de la Montaña", department: "Antioquia" },
  { label: "San José del Fragua", city: "San José del Fragua", department: "Caquetá" },
  { label: "San José del Guaviare", city: "San José del Guaviare", department: "Guaviare" },
  { label: "San José del Palmar", city: "San José del Palmar", department: "Chocó" },
  { label: "San Juan Nepomuceno", city: "San Juan Nepomuceno", department: "Bolívar" },
  { label: "San Juan de Arama", city: "San Juan de Arama", department: "Meta" },
  { label: "San Juan de Betulia", city: "San Juan de Betulia", department: "Sucre" },
  { label: "San Juan de Rioseco", city: "San Juan de Rioseco", department: "Cundinamarca" },
  { label: "San Juan de Urabá", city: "San Juan de Urabá", department: "Antioquia" },
  { label: "San Juan del Cesar", city: "San Juan del Cesar", department: "La Guajira" },
  { label: "San Juanito", city: "San Juanito", department: "Meta" },
  { label: "San Lorenzo", city: "San Lorenzo", department: "Nariño" },
  { label: "San Luis de Gaceno", city: "San Luis de Gaceno", department: "Boyacá" },
  { label: "San Luis de Palenque", city: "San Luis de Palenque", department: "Casanare" },
  { label: "San Luis, Antioquia", city: "San Luis", department: "Antioquia" },
  { label: "San Luis, Tolima", city: "San Luis", department: "Tolima" },
  { label: "San Marcos", city: "San Marcos", department: "Sucre" },
  { label: "San Martín de Loba", city: "San Martín de Loba", department: "Bolívar" },
  { label: "San Martín, Cesar", city: "San Martín", department: "Cesar" },
  { label: "San Martín, Meta", city: "San Martín", department: "Meta" },
  { label: "San Mateo", city: "San Mateo", department: "Boyacá" },
  { label: "San Miguel de Sema", city: "San Miguel de Sema", department: "Boyacá" },
  { label: "San Miguel, Putumayo", city: "San Miguel", department: "Putumayo" },
  { label: "San Miguel, Santander", city: "San Miguel", department: "Santander" },
  { label: "San Onofre", city: "San Onofre", department: "Sucre" },
  { label: "San Pablo de Borbur", city: "San Pablo de Borbur", department: "Boyacá" },
  { label: "San Pablo, Bolívar", city: "San Pablo", department: "Bolívar" },
  { label: "San Pablo, Nariño", city: "San Pablo", department: "Nariño" },
  { label: "San Pedro de Cartago", city: "San Pedro de Cartago", department: "Nariño" },
  { label: "San Pedro de Urabá", city: "San Pedro de Urabá", department: "Antioquia" },
  { label: "San Pedro de los Milagros", city: "San Pedro de los Milagros", department: "Antioquia" },
  { label: "San Pedro, Sucre", city: "San Pedro", department: "Sucre" },
  { label: "San Pedro, Valle del Cauca", city: "San Pedro", department: "Valle del Cauca" },
  { label: "San Pelayo", city: "San Pelayo", department: "Córdoba" },
  { label: "San Rafael", city: "San Rafael", department: "Antioquia" },
  { label: "San Roque", city: "San Roque", department: "Antioquia" },
  { label: "San Sebastián", city: "San Sebastián", department: "Cauca" },
  { label: "San Sebastián de Buenavista", city: "San Sebastián de Buenavista", department: "Magdalena" },
  { label: "San Vicente", city: "San Vicente", department: "Antioquia" },
  { label: "San Vicente de Chucurí", city: "San Vicente de Chucurí", department: "Santander" },
  { label: "San Vicente del Caguán", city: "San Vicente del Caguán", department: "Caquetá" },
  { label: "San Zenón", city: "San Zenón", department: "Magdalena" },
  { label: "Sandoná", city: "Sandoná", department: "Nariño" },
  { label: "Santa Ana", city: "Santa Ana", department: "Magdalena" },
  { label: "Santa Bárbara de Pinto", city: "Santa Bárbara de Pinto", department: "Magdalena" },
  { label: "Santa Bárbara, Antioquia", city: "Santa Bárbara", department: "Antioquia" },
  { label: "Santa Bárbara, Nariño", city: "Santa Bárbara", department: "Nariño" },
  { label: "Santa Bárbara, Santander", city: "Santa Bárbara", department: "Santander" },
  { label: "Santa Catalina", city: "Santa Catalina", department: "Bolívar" },
  { label: "Santa Fe de Antioquia", city: "Santa Fe de Antioquia", department: "Antioquia" },
  { label: "Santa Helena del Opón", city: "Santa Helena del Opón", department: "Santander" },
  { label: "Santa Isabel", city: "Santa Isabel", department: "Tolima" },
  { label: "Santa Lucía", city: "Santa Lucía", department: "Atlántico" },
  { label: "Santa Marta", city: "Santa Marta", department: "Magdalena" },
  { label: "Santa María, Boyacá", city: "Santa María", department: "Boyacá" },
  { label: "Santa María, Huila", city: "Santa María", department: "Huila" },
  { label: "Santa Rosa de Cabal", city: "Santa Rosa de Cabal", department: "Risaralda" },
  { label: "Santa Rosa de Osos", city: "Santa Rosa de Osos", department: "Antioquia" },
  { label: "Santa Rosa de Viterbo", city: "Santa Rosa de Viterbo", department: "Boyacá" },
  { label: "Santa Rosa del Sur", city: "Santa Rosa del Sur", department: "Bolívar" },
  { label: "Santa Rosa, Bolívar", city: "Santa Rosa", department: "Bolívar" },
  { label: "Santa Rosa, Cauca", city: "Santa Rosa", department: "Cauca" },
  { label: "Santa Rosalía", city: "Santa Rosalía", department: "Vichada" },
  { label: "Santa Sofía", city: "Santa Sofía", department: "Boyacá" },
  { label: "Santacruz", city: "Santacruz", department: "Nariño" },
  { label: "Santana", city: "Santana", department: "Boyacá" },
  { label: "Santander de Quilichao", city: "Santander de Quilichao", department: "Cauca" },
  { label: "Santiago, Norte de Santander", city: "Santiago", department: "Norte de Santander" },
  { label: "Santiago, Putumayo", city: "Santiago", department: "Putumayo" },
  { label: "Santo Domingo", city: "Santo Domingo", department: "Antioquia" },
  { label: "Santo Domingo de Silos", city: "Santo Domingo de Silos", department: "Norte de Santander" },
  { label: "Santo Tomás", city: "Santo Tomás", department: "Atlántico" },
  { label: "Santuario", city: "Santuario", department: "Risaralda" },
  { label: "Sapuyes", city: "Sapuyes", department: "Nariño" },
  { label: "Saravena", city: "Saravena", department: "Arauca" },
  { label: "Sardinata", city: "Sardinata", department: "Norte de Santander" },
  { label: "Sasaima", city: "Sasaima", department: "Cundinamarca" },
  { label: "Sativanorte", city: "Sativanorte", department: "Boyacá" },
  { label: "Sativasur", city: "Sativasur", department: "Boyacá" },
  { label: "Segovia", city: "Segovia", department: "Antioquia" },
  { label: "Sesquilé", city: "Sesquilé", department: "Cundinamarca" },
  { label: "Sevilla", city: "Sevilla", department: "Valle del Cauca" },
  { label: "Siachoque", city: "Siachoque", department: "Boyacá" },
  { label: "Sibaté", city: "Sibaté", department: "Cundinamarca" },
  { label: "Sibundoy", city: "Sibundoy", department: "Putumayo" },
  { label: "Silvania", city: "Silvania", department: "Cundinamarca" },
  { label: "Silvia", city: "Silvia", department: "Cauca" },
  { label: "Simacota", city: "Simacota", department: "Santander" },
  { label: "Simijaca", city: "Simijaca", department: "Cundinamarca" },
  { label: "Simití", city: "Simití", department: "Bolívar" },
  { label: "Sincelejo", city: "Sincelejo", department: "Sucre" },
  { label: "Sincé", city: "Sincé", department: "Sucre" },
  { label: "Sipí", city: "Sipí", department: "Chocó" },
  { label: "Sitionuevo", city: "Sitionuevo", department: "Magdalena" },
  { label: "Soacha", city: "Soacha", department: "Cundinamarca" },
  { label: "Soatá", city: "Soatá", department: "Boyacá" },
  { label: "Socha", city: "Socha", department: "Boyacá" },
  { label: "Socotá", city: "Socotá", department: "Boyacá" },
  { label: "Sogamoso", city: "Sogamoso", department: "Boyacá" },
  { label: "Solano", city: "Solano", department: "Caquetá" },
  { label: "Soledad", city: "Soledad", department: "Atlántico" },
  { label: "Solita", city: "Solita", department: "Caquetá" },
  { label: "Somondoco", city: "Somondoco", department: "Boyacá" },
  { label: "Sonsón", city: "Sonsón", department: "Antioquia" },
  { label: "Sopetrán", city: "Sopetrán", department: "Antioquia" },
  { label: "Soplaviento", city: "Soplaviento", department: "Bolívar" },
  { label: "Sopó", city: "Sopó", department: "Cundinamarca" },
  { label: "Sora", city: "Sora", department: "Boyacá" },
  { label: "Soracá", city: "Soracá", department: "Boyacá" },
  { label: "Sotaquirá", city: "Sotaquirá", department: "Boyacá" },
  { label: "Sotará", city: "Sotará", department: "Cauca" },
  { label: "Suaita", city: "Suaita", department: "Santander" },
  { label: "Suaza", city: "Suaza", department: "Huila" },
  { label: "Subachoque", city: "Subachoque", department: "Cundinamarca" },
  { label: "Sucre, Cauca", city: "Sucre", department: "Cauca" },
  { label: "Sucre, Santander", city: "Sucre", department: "Santander" },
  { label: "Sucre, Sucre", city: "Sucre", department: "Sucre" },
  { label: "Suesca", city: "Suesca", department: "Cundinamarca" },
  { label: "Supatá", city: "Supatá", department: "Cundinamarca" },
  { label: "Supía", city: "Supía", department: "Caldas" },
  { label: "Suratá", city: "Suratá", department: "Santander" },
  { label: "Susa", city: "Susa", department: "Cundinamarca" },
  { label: "Susacón", city: "Susacón", department: "Boyacá" },
  { label: "Sutamarchán", city: "Sutamarchán", department: "Boyacá" },
  { label: "Sutatausa", city: "Sutatausa", department: "Cundinamarca" },
  { label: "Sutatenza", city: "Sutatenza", department: "Boyacá" },
  { label: "Suán", city: "Suán", department: "Atlántico" },
  { label: "Suárez, Cauca", city: "Suárez", department: "Cauca" },
  { label: "Suárez, Tolima", city: "Suárez", department: "Tolima" },
  { label: "Sácama", city: "Sácama", department: "Casanare" },
  { label: "Sáchica", city: "Sáchica", department: "Boyacá" },
  { label: "Tabio", city: "Tabio", department: "Cundinamarca" },
  { label: "Tadó", city: "Tadó", department: "Chocó" },
  { label: "Talaigua Nuevo", city: "Talaigua Nuevo", department: "Bolívar" },
  { label: "Tamalameque", city: "Tamalameque", department: "Cesar" },
  { label: "Tame", city: "Tame", department: "Arauca" },
  { label: "Taminango", city: "Taminango", department: "Nariño" },
  { label: "Tangua", city: "Tangua", department: "Nariño" },
  { label: "Taraira", city: "Taraira", department: "Vaupés" },
  { label: "Tarazá", city: "Tarazá", department: "Antioquia" },
  { label: "Tarqui", city: "Tarqui", department: "Huila" },
  { label: "Tarso", city: "Tarso", department: "Antioquia" },
  { label: "Tasco", city: "Tasco", department: "Boyacá" },
  { label: "Tauramena", city: "Tauramena", department: "Casanare" },
  { label: "Tausa", city: "Tausa", department: "Cundinamarca" },
  { label: "Tello", city: "Tello", department: "Huila" },
  { label: "Tena", city: "Tena", department: "Cundinamarca" },
  { label: "Tenerife", city: "Tenerife", department: "Magdalena" },
  { label: "Tenjo", city: "Tenjo", department: "Cundinamarca" },
  { label: "Tenza", city: "Tenza", department: "Boyacá" },
  { label: "Teorama", city: "Teorama", department: "Norte de Santander" },
  { label: "Teruel", city: "Teruel", department: "Huila" },
  { label: "Tesalia", city: "Tesalia", department: "Huila" },
  { label: "Tibacuy", city: "Tibacuy", department: "Cundinamarca" },
  { label: "Tibaná", city: "Tibaná", department: "Boyacá" },
  { label: "Tibasosa", city: "Tibasosa", department: "Boyacá" },
  { label: "Tibirita", city: "Tibirita", department: "Cundinamarca" },
  { label: "Tibú", city: "Tibú", department: "Norte de Santander" },
  { label: "Tierralta", city: "Tierralta", department: "Córdoba" },
  { label: "Timaná", city: "Timaná", department: "Huila" },
  { label: "Timbiquí", city: "Timbiquí", department: "Cauca" },
  { label: "Timbío", city: "Timbío", department: "Cauca" },
  { label: "Tinjacá", city: "Tinjacá", department: "Boyacá" },
  { label: "Tipacoque", city: "Tipacoque", department: "Boyacá" },
  { label: "Tiquisio", city: "Tiquisio", department: "Bolívar" },
  { label: "Titiribí", city: "Titiribí", department: "Antioquia" },
  { label: "Toca", city: "Toca", department: "Boyacá" },
  { label: "Tocaima", city: "Tocaima", department: "Cundinamarca" },
  { label: "Tocancipá", city: "Tocancipá", department: "Cundinamarca" },
  { label: "Togüí", city: "Togüí", department: "Boyacá" },
  { label: "Toledo, Antioquia", city: "Toledo", department: "Antioquia" },
  { label: "Toledo, Norte de Santander", city: "Toledo", department: "Norte de Santander" },
  { label: "Tolú", city: "Tolú", department: "Sucre" },
  { label: "Tolú Viejo", city: "Tolú Viejo", department: "Sucre" },
  { label: "Tona", city: "Tona", department: "Santander" },
  { label: "Topaipí", city: "Topaipí", department: "Cundinamarca" },
  { label: "Toribío", city: "Toribío", department: "Cauca" },
  { label: "Toro", city: "Toro", department: "Valle del Cauca" },
  { label: "Tota", city: "Tota", department: "Boyacá" },
  { label: "Totoró", city: "Totoró", department: "Cauca" },
  { label: "Trinidad", city: "Trinidad", department: "Casanare" },
  { label: "Trujillo", city: "Trujillo", department: "Valle del Cauca" },
  { label: "Tubará", city: "Tubará", department: "Atlántico" },
  { label: "Tuchín", city: "Tuchín", department: "Córdoba" },
  { label: "Tuluá", city: "Tuluá", department: "Valle del Cauca" },
  { label: "Tumaco", city: "Tumaco", department: "Nariño" },
  { label: "Tunja", city: "Tunja", department: "Boyacá" },
  { label: "Tununguá", city: "Tununguá", department: "Boyacá" },
  { label: "Turbaco", city: "Turbaco", department: "Bolívar" },
  { label: "Turbaná", city: "Turbaná", department: "Bolívar" },
  { label: "Turbo", city: "Turbo", department: "Antioquia" },
  { label: "Turmequé", city: "Turmequé", department: "Boyacá" },
  { label: "Tuta", city: "Tuta", department: "Boyacá" },
  { label: "Tutazá", city: "Tutazá", department: "Boyacá" },
  { label: "Támara", city: "Támara", department: "Casanare" },
  { label: "Támesis", city: "Támesis", department: "Antioquia" },
  { label: "Tópaga", city: "Tópaga", department: "Boyacá" },
  { label: "Túquerres", city: "Túquerres", department: "Nariño" },
  { label: "Ubalá", city: "Ubalá", department: "Cundinamarca" },
  { label: "Ubaque", city: "Ubaque", department: "Cundinamarca" },
  { label: "Ubaté", city: "Ubaté", department: "Cundinamarca" },
  { label: "Ulloa", city: "Ulloa", department: "Valle del Cauca" },
  { label: "Une", city: "Une", department: "Cundinamarca" },
  { label: "Unguía", city: "Unguía", department: "Chocó" },
  { label: "Unión Panamericana", city: "Unión Panamericana", department: "Chocó" },
  { label: "Uramita", city: "Uramita", department: "Antioquia" },
  { label: "Uribia", city: "Uribia", department: "La Guajira" },
  { label: "Urrao", city: "Urrao", department: "Antioquia" },
  { label: "Urumita", city: "Urumita", department: "La Guajira" },
  { label: "Usiacurí", city: "Usiacurí", department: "Atlántico" },
  { label: "Valdivia", city: "Valdivia", department: "Antioquia" },
  { label: "Valencia", city: "Valencia", department: "Córdoba" },
  { label: "Valle de San José", city: "Valle de San José", department: "Santander" },
  { label: "Valle de San Juan", city: "Valle de San Juan", department: "Tolima" },
  { label: "Valle del Guamuez", city: "Valle del Guamuez", department: "Putumayo" },
  { label: "Valledupar", city: "Valledupar", department: "Cesar" },
  { label: "Valparaíso, Antioquia", city: "Valparaíso", department: "Antioquia" },
  { label: "Valparaíso, Caquetá", city: "Valparaíso", department: "Caquetá" },
  { label: "Vegachí", city: "Vegachí", department: "Antioquia" },
  { label: "Venadillo", city: "Venadillo", department: "Tolima" },
  { label: "Venecia, Antioquia", city: "Venecia", department: "Antioquia" },
  { label: "Venecia, Cundinamarca", city: "Venecia", department: "Cundinamarca" },
  { label: "Ventaquemada", city: "Ventaquemada", department: "Boyacá" },
  { label: "Vergara", city: "Vergara", department: "Cundinamarca" },
  { label: "Versalles", city: "Versalles", department: "Valle del Cauca" },
  { label: "Vetas", city: "Vetas", department: "Santander" },
  { label: "Vianí", city: "Vianí", department: "Cundinamarca" },
  { label: "Victoria", city: "Victoria", department: "Caldas" },
  { label: "Vigía del Fuerte", city: "Vigía del Fuerte", department: "Antioquia" },
  { label: "Vijes", city: "Vijes", department: "Valle del Cauca" },
  { label: "Villa Caro", city: "Villa Caro", department: "Norte de Santander" },
  { label: "Villa Rica", city: "Villa Rica", department: "Cauca" },
  { label: "Villa de Leyva", city: "Villa de Leyva", department: "Boyacá" },
  { label: "Villa del Rosario", city: "Villa del Rosario", department: "Norte de Santander" },
  { label: "Villagarzón", city: "Villagarzón", department: "Putumayo" },
  { label: "Villagómez", city: "Villagómez", department: "Cundinamarca" },
  { label: "Villahermosa", city: "Villahermosa", department: "Tolima" },
  { label: "Villamaría", city: "Villamaría", department: "Caldas" },
  { label: "Villanueva, Bolívar", city: "Villanueva", department: "Bolívar" },
  { label: "Villanueva, Casanare", city: "Villanueva", department: "Casanare" },
  { label: "Villanueva, La Guajira", city: "Villanueva", department: "La Guajira" },
  { label: "Villanueva, Santander", city: "Villanueva", department: "Santander" },
  { label: "Villapinzón", city: "Villapinzón", department: "Cundinamarca" },
  { label: "Villarrica", city: "Villarrica", department: "Tolima" },
  { label: "Villavicencio", city: "Villavicencio", department: "Meta" },
  { label: "Villavieja", city: "Villavieja", department: "Huila" },
  { label: "Villeta", city: "Villeta", department: "Cundinamarca" },
  { label: "Viotá", city: "Viotá", department: "Cundinamarca" },
  { label: "Viracachá", city: "Viracachá", department: "Boyacá" },
  { label: "Vista Hermosa", city: "Vista Hermosa", department: "Meta" },
  { label: "Viterbo", city: "Viterbo", department: "Caldas" },
  { label: "Vélez", city: "Vélez", department: "Santander" },
  { label: "Yacopí", city: "Yacopí", department: "Cundinamarca" },
  { label: "Yacuanquer", city: "Yacuanquer", department: "Nariño" },
  { label: "Yaguará", city: "Yaguará", department: "Huila" },
  { label: "Yalí", city: "Yalí", department: "Antioquia" },
  { label: "Yarumal", city: "Yarumal", department: "Antioquia" },
  { label: "Yolombó", city: "Yolombó", department: "Antioquia" },
  { label: "Yondó", city: "Yondó", department: "Antioquia" },
  { label: "Yopal", city: "Yopal", department: "Casanare" },
  { label: "Yotoco", city: "Yotoco", department: "Valle del Cauca" },
  { label: "Yumbo", city: "Yumbo", department: "Valle del Cauca" },
  { label: "Zambrano", city: "Zambrano", department: "Bolívar" },
  { label: "Zapatoca", city: "Zapatoca", department: "Santander" },
  { label: "Zapayán", city: "Zapayán", department: "Magdalena" },
  { label: "Zaragoza", city: "Zaragoza", department: "Antioquia" },
  { label: "Zarzal", city: "Zarzal", department: "Valle del Cauca" },
  { label: "Zetaquira", city: "Zetaquira", department: "Boyacá" },
  { label: "Zipacón", city: "Zipacón", department: "Cundinamarca" },
  { label: "Zipaquirá", city: "Zipaquirá", department: "Cundinamarca" },
  { label: "Zona Bananera", city: "Zona Bananera", department: "Magdalena" },
  { label: "Ábrego", city: "Ábrego", department: "Norte de Santander" },
  { label: "Íquira", city: "Íquira", department: "Huila" },
  { label: "Úmbita", city: "Úmbita", department: "Boyacá" },
  { label: "Útica", city: "Útica", department: "Cundinamarca" },
];
